### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by iJunkie22**
Here are some general improvements I've made to my fork of your repo... feel free to merge them into your own :)

### CODE REVIEW

**Comment by Magister** [comment]
Looks like everything is ok, thanks!
btw, is this project really useful now, after introduction of signature checking in the recent versions of Opera?

**Comment by iJunkie22** [comment]
Yes. I use it for modding Chromium. https://gist.github.com/iJunkie22/942c9875d0abe9de6721#file-chromium_hacks-md

**Comment by iJunkie22** [comment]
And btw one of the reasons for 378e886a448e7e42f3e3711924700a53a687accd was to open up the possibility of using these packages as python modules. My plan is to make a modding utility for Chromium.

**Comment by Magister** [comment]
Ah, that's good. Happy it's useful for you!

**Pull request merged**
